### PR TITLE
feat: add AWS guide

### PR DESCRIPTION
**Pull request by blakegong**
This actually doesn't have much about the actual migration steps, but instead a "checklist" kinda thing to help people make better decisions. Hope it makes sense!

The actual migration is either too easy (if you have experience) or too hard (first time Pulumi + ECS), so it's either you know everything or you need our help, thus didn't elaborate too much on that.

### CODE REVIEW

**Review by karrui — APPROVED** [review]
I assume we are not going to give an example of how Bright migrated to AWS? Is it because everything is on a case by case basis? Wondering if we should have some basic guide on what is needed to translate to an AWS deployment, such as what to change in environment variables, etc. or would it be self explanatory?

**Comment by blakegong** [comment]
It's very hard to give a good example to an audience with a different level of understanding to Pulumi and ECS I think. For those who understands them, the linked 2 PRs should be enough (e.g. Daryl and Caleb migrated Pixie mostly without my help, by just copying from Bright's example). But for others, we'd probably need to start from "what is Pulumi" and "what is ECS". No good documentation can cover all these needs I think. I really think if people are not as comfortable as Daryl and Caleb with their migration, they should talk to us first, and the doc was written to herd people into doing that.

What I do want you to help with, is whether all the points on why Vercel and why AWS make sense to you? Have I missed anything there that you think should also be considered? 🙏 😄

**Comment by blakegong** [comment]
And trust me I've tried to write a more detailed guide on the actual migration 😂 And just scratched that cuz I really couldn't make that work.

In the end I really felt it's more important to make people understand why they need to move to AWS, instead of "how". The direction has to be correct first. The "how" is just implementation details.

**Comment by karrui** [comment]
> In the end I really felt it's more important to make people understand why they need to move to AWS, instead of "how". The direction has to be correct first. The "how" is just implementation details.

For example, we may want to highlight the changes needed by the application that moving to AWS unlocks (maybe how to inject DD agent, etc?). Or even how to bundle the application to allow for deployment on AWS. 

Or suggesting ways to bundle up applications to be deployed in AWS, such as [OpenNext](https://open-next.js.org/), and how that could be achieved, I guess. Should we document how Bright migrated as a case study instead of linking to the PRs too?

But I see your point too, so lgtm haha!

**Comment by blakegong** [comment]
Yeah I see your point too haha.

> For example, we may want to highlight the changes needed by the application that moving to AWS unlocks (maybe how to inject DD agent, etc?). Or even how to bundle the application to allow for deployment on AWS.

I don't wanna do it for now cuz Pixie didn't need these and they still achieved all these without much consultation. To me these things are really "if you don't yet know how to do it, it's easier to talk it through cuz reading a doc will still make one confused".

> Or suggesting ways to bundle up applications to be deployed in AWS, such as [OpenNext](https://open-next.js.org/), and how that could be achieved, I guess. Should we document how Bright migrated as a case study instead of linking to the PRs too?

My view on OpenNext is that it only solves part of the problems mentioned in `Common reasons to migrate away from Vercel`, but is missing some, especially `cost reduction` -> I'd expect the cost of running on Vercel vs our own Lambda to be on the same scale. We might save ~30% but cannot be more drastic thus most of the time real cost reduction cannot be achieved by the move. Plus it's coupled with SST, which makes me worried about how we'd then recommend people to create proper RDS/Redis etc. with ease since they only exist in Pulumi components. It's a tradeoff between "recommending something tooling team knows how to operate" vs. "recommending something that should fit the bill but you are on your own after that". I think having our backing should still be essential to whatever we provide?

Thanks for the discussion sir! I'm gonna merge this then. I will still respond to comments here/or we can move the convo to Slack too.

**Pull request merged**
